//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buoi9
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhPho
    {
        public ThanhPho()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public string ThanhPho1 { get; set; }
        public string TenThanhPho { get; set; }
    
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
